### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by mattam82** [gares/opam-coq-shell#1]
Which shell are you using? My opam-coq fails with

/Users/mat/bin/opam-coq: line 329: syntax error: unexpected end of file

**Comment by mattam82** [comment]
Ok, found the issue. Each ending "EOT" should be on a line with no spaces.

**Comment by gares** [comment]
This is on OSX? In theory <<EOT requires EOT to be at the beginning of the line, but <<-EOT should accept spaces (http://en.wikipedia.org/wiki/Here_document#Unix_shells)... I'll fix that, thanks for reporting.

**Comment by mattam82** [comment]
Ah Ok, on OS X yeah. I'd be curious if you can try opam install
coq:equations-fpred once you merge my PR too.
Have a great week-end!
-- Matthieu
