### ISSUE TITLE
curl failing

### ISSUE THREAD

**Issue by mattam82** [gares/opam-coq-shell#2]
coq-core-dev] Downloading http://ssr.msr-inria.inria.fr/~gares/coq-opam-archive/core-dev/urls.txt
[ERROR] curl: code 404 while downloading http://ssr.msr-inria.inria.fr/~gares/coq-opam-archive/core-dev/urls.txt

**Comment by gares** [comment]
fixed

**Comment by mattam82** [comment]
Thanks!
